/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DomingoRouteImport } from './routes/domingo'
import { Route as ImprimirRouteImport } from './routes/imprimir'
import { Route as IndividualRouteImport } from './routes/individual'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DomingoRoute = DomingoRouteImport.update({
  id: '/domingo',
  path: '/domingo',
  getParentRoute: () => rootRouteImport,
} as any)
const ImprimirRoute = ImprimirRouteImport.update({
  id: '/imprimir',
  path: '/imprimir',
  getParentRoute: () => rootRouteImport,
} as any)
const IndividualRoute = IndividualRouteImport.update({
  id: '/individual',
  path: '/individual',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/domingo': typeof DomingoRoute
  '/imprimir': typeof ImprimirRoute
  '/individual': typeof IndividualRoute
  '/admin': typeof AuthenticatedAdminRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/domingo': typeof DomingoRoute
  '/imprimir': typeof ImprimirRoute
  '/individual': typeof IndividualRoute
  '/admin': typeof AuthenticatedAdminRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/domingo': typeof DomingoRoute
  '/imprimir': typeof ImprimirRoute
  '/individual': typeof IndividualRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/domingo' | '/imprimir' | '/individual' | '/admin'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/domingo' | '/imprimir' | '/individual' | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/domingo'
    | '/imprimir'
    | '/individual'
    | '/_authenticated/admin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DomingoRoute: typeof DomingoRoute
  ImprimirRoute: typeof ImprimirRoute
  IndividualRoute: typeof IndividualRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domingo': {
      id: '/domingo'
      path: '/domingo'
      fullPath: '/domingo'
      preLoaderRoute: typeof DomingoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imprimir': {
      id: '/imprimir'
      path: '/imprimir'
      fullPath: '/imprimir'
      preLoaderRoute: typeof ImprimirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/individual': {
      id: '/individual'
      path: '/individual'
      fullPath: '/individual'
      preLoaderRoute: typeof IndividualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DomingoRoute: DomingoRoute,
  ImprimirRoute: ImprimirRoute,
  IndividualRoute: IndividualRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
